### ISSUE TITLE
missing deps

### ISSUE THREAD

**Issue by Et7f3** [gsauthof/adf2pdf#1]
I needed to do

```
pip install configargparse img2pdf pypdf2
```

so the package could be installed could you publish a version with those dips mentioned or make them optional so other doesn't have to guess ?

**Comment by gsauthof** [comment]
Thank you for letting me know!

setup.py currently imports adf2pdf to get the version number, such that the version number can be maintained in one place.

As an unintended side effect, that import pulls in adf2pdf's dependencies before it's installed.

I'll push a fix.

**Comment by gsauthof** [comment]
Release 0.8.3 contains the fix and is now available on PyPI.

**Comment by Et7f3** [comment]
> setup.py currently imports adf2pdf to get the version number, such that the version number can be maintained in one place.

thanks for your prompt help

you can create a version.py file without dependency so you can keep best of both world. If you are ok with two version it can be ok 👍🏻.

I will test tomorrow (I saw the commit and it should be ok) and report if I see other issues.

**Comment by gsauthof** [comment]
When changing it I looked at some alternative approaches but at the end went for the simplest way, i.e. simply having to update 2 version numbers.

Just having an extra file for the version number felt like overkill and AFAICS wouldn't be something I could keep using if/when I replace setup.py with pyproject.toml.

Other schemes I came across seemed to be too clever and/or too complex.

Since the release frequency isn't that high having to change two locations for a release isn't a big deal.
When that changes one could even automate/script that version bumping.
